### ISSUE TITLE
port的设置有什么注意点吗？

### ISSUE THREAD

**Issue by Abeautifulsnow** [githubw2015/crawler-boss#1]
我设置如下：
```go
const (
	seleniumPath     = `/Users/dapeng/Downloads/others/selenium-server-4.0.0-beta-4.jar`
	chromeDriverPath = `/Applications/Google\ Chrome.app/Contents/chromedriver`
	port             = 4444
)
```
它报错：
```bash
panic: server did not respond on port 4444

goroutine 203 [running]:
main.main.func1(0x14de540, 0xc000250fa0, 0x145b4b5, 0x4, 0x60571c4, 0x145d4fe, 0x6)
        /Users/dapeng/Documents/code/go/src/proj/crawler/main.go:89 +0x10db
created by main.main
        /Users/dapeng/Documents/code/go/src/proj/crawler/main.go:87 +0x22c
exit status 2
```

-------------------

我设置port为 `8080`：
```go
const (
	seleniumPath     = `/Users/dapeng/Downloads/others/selenium-server-4.0.0-beta-4.jar`
	chromeDriverPath = `/Applications/Google\ Chrome.app/Contents/chromedriver`
	port             = 8080
)
```
它报这个错：
```bash
panic: unknown error - 33: Unable to create new service: ChromeDriverService
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
System info: host: 'B-K1H5JHD2-2305', ip: 'fe80:0:0:0:1c8b:e051:22cd:551a%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '11.4', java.version: '16.0.1'Driver info: driver.version: unknown

goroutine 36 [running]:
main.main.func1(0x0, 0x0, 0x145cda2, 0x6, 0x60571c4, 0x145d4fe, 0x6)
        /Users/dapeng/Documents/code/go/src/proj/crawler/main.go:123 +0x10bf
created by main.main
        /Users/dapeng/Documents/code/go/src/proj/crawler/main.go:87 +0x22c
exit status 2
```

**java直接运行jar包**

```bash
➜  ~ java -jar Downloads/others/selenium-server-4.0.0-beta-4.jar hub
18:56:59.414 INFO [LoggingOptions.configureLogEncoding] - Using the system default encoding
18:56:59.420 INFO [OpenTelemetryTracer.createTracer] - Using OpenTelemetry for tracing
18:56:59.553 INFO [BoundZmqEventBus.<init>] - XPUB binding to [binding to tcp://*:4442, advertising as tcp://[fe80:0:0:0:1c8b:e051:22cd:551a%en0]:4442], XSUB binding to [binding to tcp://*:4443, advertising as tcp://[fe80:0:0:0:1c8b:e051:22cd:551a%en0]:4443]
18:56:59.621 INFO [UnboundZmqEventBus.<init>] - Connecting to tcp://[fe80:0:0:0:1c8b:e051:22cd:551a%en0]:4442 and tcp://[fe80:0:0:0:1c8b:e051:22cd:551a%en0]:4443
18:56:59.650 INFO [UnboundZmqEventBus.<init>] - Sockets created
18:57:00.655 INFO [UnboundZmqEventBus.<init>] - Event bus ready
18:57:01.353 INFO [Hub.execute] - Started Selenium Hub 4.0.0-beta-4 (revision 29f46d02dd): http://192.168.1.126:4444
```

---------------------------

我该怎么搞？「PS：这个运行chromedriver还需要安装java...感觉比python的难用好多😂」会不会是jar包、java、或者chrome的版本原因？

> 信息罗列

- java: openjdk version "16.0.1" 2021-04-20
- chrome:  91.0.4472.114（正式版本） (x86_64)
- selenium-server-jar包: selenium-server-4.0.0-beta-4.jar

**Comment by githubw2015** [comment]
port  只要系不占用windows 系统的端口都行，比方说 8081  8082 8083 等等

**Comment by githubw2015** [comment]
chromedriver.exe  驱动包到这里下载:  https://npm.taobao.org/mirrors/chromedriver/92.0.4515.43/   
selenium-server-standalone-3.9.1jar    包可以到这里下载 https://www.cr173.com/soft/416787.html
你可以试试在 winodws 环境试试，成功之后，再考虑  Linux
chromedriver 路径注意以下。

**Comment by githubw2015** [comment]
const (
	seleniumPath    = `./package/selenium-server-standalone-3.9.1.jar`
	geckoDriverPath = `./package/chromedriver`
	port            = 9515
)
端口写死成 9515 吧，驱动那边默认端口。

![image](https://user-images.githubusercontent.com/16487020/126893155-0189f38a-0d19-44f4-9138-a1f1aceb3131.png)


然后在 linux 下是可以运行的。

**Comment by Abeautifulsnow** [comment]
ok了。jar包换成了3.141.59版本，java16运行不了这个jar，我又回退到java8，然后ok了。。。😂
